# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'platonWeb3Demo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'PlatonWeb3', :path => '../'
#  pod 'BigInt', '~> 4.0'
##  pod 'CryptoSwift', '~> 0.8'
#  pod 'secp256k1.swift', '~> 0.1'
#  pod 'Localize-Swift', '~> 2.0'
  pod 'SVProgressHUD'

#  target 'platonWeb3DemoUITests' do
#    inherit! :search_paths
#    # Pods for testing
#  end
  
  target 'platonWeb3DemoTests' do
      inherit! :search_paths
      # Pods for testing
  end

end
